sudo: enabled
services: docker
dist: trusty
language: ruby

os:
  - linux

rvm:
  - 2.5.5

before_install:
  - sudo apt-get update && sudo apt-get install -y curl
  - curl -L -o packer_1.4.0_linux_amd64.zip https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip
  - sudo unzip packer_1.4.0_linux_amd64.zip
  - sudo cp packer /usr/local/bin/
  - rm packer_1.4.0_linux_amd64.zip
  - curl -L -o terraform_0.11.13_linux_amd64.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
  - sudo unzip terraform_0.11.13_linux_amd64.zip
  - sudo cp terraform /usr/local/bin
  - rm -fv terraform_0.11.13_linux_amd64.zip

install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip libssl-dev
  - sudo pip install --upgrade pip setuptools wheel
  - sudo pip install ansible
  - cd src
  - bundle install
  - bundle exec rake
  - cd ..

jobs:
  include:
    - stage: "Tests"
      name: "Ruby Tests"
      script:
        - make local-tests