sudo: enabled
services: docker
dist: trusty
language: ruby

os:
  - linux

rvm:
  - 2.5.5

before_install:
  - echo $GOOGLE_PACKER_CREDENTIALS > $TRAVIS_BUILD_DIR/demo-infra.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/demo-infra.json
  - sudo apt-get update && sudo apt-get install -y curl
  - mkdir bin && cd bin
  - curl -L -o packer_1.4.0_linux_amd64.zip https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip
  - sudo unzip packer_1.4.0_linux_amd64.zip
  - sudo mv packer /usr/local/bin/
  - rm packer_1.4.0_linux_amd64.zip
  - curl -L -o terraform_0.11.13_linux_amd64.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
  - sudo unzip terraform_0.11.13_linux_amd64.zip
  - sudo mv terraform /usr/local/bin
  - rm -fv terraform_0.11.13_linux_amd64.zip
  - cd ..

install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip libssl-dev
  - sudo pip install --upgrade pip setuptools wheel
  - sudo pip install ansible
  - cd src
  - bundle install

jobs:
  include:
    - stage: "Tests App"
      name: "Ruby Tests"
      script:
        - bundle exec rake
    - stage: "Build Container Image"
      name: "Build and Push Docker Image"
      script:
        - rm -fv Gemfile.lock
        - export HASH=`date +%d%m%Y%H%M%S`
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t perylemke/apery:$HASH .
        - docker tag perylemke/apery:$HASH perylemke/apery:latest
        - docker push perylemke/apery:$HASH
        - docker push perylemke/apery
      if: branch = master
    - stage: "Build VM image"
      name: "Build VM image with Packer"
      script:
        - cd ..
        - make build
      if: branch = master
    - stage: "Deploy"
      name: "Deploy with Terraform"
      script:
        - make init
        - make deploy
      if: branch = master
