---
# handlers file for ansible
- name: Ensure start docker
  systemd:
    state: started
    name: docker
    enabled: yes
  listen: "start docker"
  become: true

- name: Ensure start apery
  systemd:
    state: started
    daemon_reload: yes
    name: apery
    enabled: yes
    masked: no
  listen: "start apery"
  become: true
