---
# handlers file for ansible
- name: Ensure start docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes
  listen: "restart docker"
  become: true

- name: Ensure start stackdriver
  systemd:
    state: started
    name: stackdriver-agent
    enabled: yes
  listen: "start stackdriver"
  become: true

- name: Ensure start apery
  systemd:
    state: started
    daemon_reload: yes
    name: apery
    enabled: yes
    masked: no
  listen: "start apery"
  become: true
