---
env: "{{ lookup('env', 'DEPLOY_ENV')}}"

docker_username: "{{ lookup('env', 'DOCKER_USERNAME')}}"

docker_password: "{{ lookup('env', 'DOCKER_PASSWORD')}}"

docker_apt_repository: >
  deb [arch=amd64]
  https://download.docker.com/linux/debian stretch stable
