---
- name: install packages depencies for Docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2 
      - software-properties-common
      - python-docker
    update_cache: true

- name: Upgrade System
  command: echo "LC_ALL=en_US.UTF-8" >> /etc/environment && 
           localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 &&
           LANG=en_US.utf8

- name: Kernel tunning
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repo 
  apt_repository:
    repo: "{{ docker_apt_repository }}"

- name: Update repositories cache and install "docker" package
  apt:
    name: docker-ce
    update_cache: yes

- name: registry in Docker-Hub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Add specific users to "docker" group
  user:
    name: "admin"
    groups: "docker"
    append: True

- name: Allow 'admin' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes

- name: Apery | Create Unit file
  template: src=apery.service.j2 dest=/etc/systemd/system/apery.service mode=0644
  become: true

- name: restart service Apery
  systemd:
    state: started
    daemon_reload: true
    name: apery
    enabled: true
    masked: false
  become: true
