---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: immutable-infra-molecule-tdd
    zone: us-central1-c
    machine_type: f1-micro
    image: debian-9
    network: demo-apery-${DEPLOY_ENV}
    subnetwork: demo-apery-${DEPLOY_ENV}
    tags: ssh
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    sudo: True
  lint:
    name: flake8
