---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

  roles:
    - role: ansible

  post_tasks:
    - name: Ensure apery is running
      uri:
        url: http://127.0.0.1/status
        status_code: 200
      register: result
      until: result.status == 200
      retries: 3
      delay: 1
